server:
  port: 80
spring:
  profiles:
      include: API-KEY
  datasource:
    url: jdbc:mariadb://computer-academy-erp.cxdjlccswbih.ap-northeast-2.rds.amazonaws.com:3306/test
    driver-class-name: org.mariadb.jdbc.Driver
    username: nowerp
    password: dlwps1331
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: true
mybatis:
  config-location: classpath:mybatis-config.xml
