server: 
  port: 8083
spring:
  datasource:
    url: jdbc:mariadb://computer-academy-erp.cxdjlccswbih.ap-northeast-2.rds.amazonaws.com:3306/computer_academy_erp
    driver-class-name: org.mariadb.jdbc.Driver
    username: nowerp
    password: nowerp1331
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
